AsyncWebServerRequest call(AuthManager& auth, String path, int method = HTTP_GET, String cookie = "", std::map<String, Header> params = {}, bool ap = false, bool header = true, String bearer = "") {
    AsyncWebServerRequest request;
    request.path = path; request.verb = method; request.params = params; request.socket.ip = ap ? 2 : 1;
    if (!bearer.empty()) request.headers["Authorization"] = {"Bearer " + bearer};
    if (header) request.headers["X-OpenNeato"] = {"1"};
    if (!cookie.empty()) request.headers["Cookie"] = {cookie};
    if (auth.authorize(&request)) {
        if (path.startsWith("/api/auth/") || path.startsWith("/api/users")) auth.handle(&request);
        else request.result.status = 200;
    }
    return request;
}
String login(AuthManager& auth, const String& name, const String& password = "correct horse battery") {
    ticks += 4000;
    auto response = call(auth, "/api/auth/login", HTTP_POST, "", {{"username", {name}}, {"password", {password}}});
    assert(response.result.status == 200);
    auto cookie = response.result.headers.at("Set-Cookie");
    assert(cookie.find("HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000") != String::npos);
    return cookie.substring(0, cookie.indexOf(';'));
}
int main() {
    Preferences prefs; DataLogger logger; AuthManager auth(prefs, logger); auth.begin();
    assert(call(auth, "/api/state").result.status == 200);
    epoch = 0;
    assert(call(auth, "/api/settings").result.status == 200);
    assert(call(auth, "/api/clean", HTTP_POST).result.status == 200);
    epoch = 1800000000;
    assert(call(auth, "/api/auth/me").result.body.find("\"authEnabled\":false") != String::npos);
    assert(call(auth, "/api/auth/settings", HTTP_PUT, "", {{"enabled", {"true"}}}).result.status == 409);
    assert(call(auth, "/api/auth/setup", HTTP_POST, "", {{"username", {"root"}}, {"password", {"correct horse battery"}}}, false, false).result.status == 403);
    assert(call(auth, "/api/auth/setup", HTTP_POST, "", {{"username", {"root"}}, {"password", {"correct horse battery"}}}).result.status == 200);
    assert(call(auth, "/api/auth/settings", HTTP_PUT, "", {{"enabled", {"true"}}}).result.status == 200);
    assert(call(auth, "/api/state").result.status == 401);
    auto admin = login(auth, "root");
    assert(call(auth, "/api/auth/setup", HTTP_POST).result.status == 401);
    for (const auto& role : {"Viewer", "Operator"}) {
        assert(call(auth, "/api/users", HTTP_POST, admin, {{"username", {role}}, {"password", {"correct horse battery"}}, {"role", {role}}}).result.status == 200);
        auto cookie = login(auth, role);
        assert(call(auth, "/api/state", HTTP_GET, cookie).result.status == 200);
        assert(call(auth, "/api/history", HTTP_GET, cookie).result.status == 200);
        assert(call(auth, "/api/logs", HTTP_GET, cookie).result.status == 200);
        assert(call(auth, "/api/clean", HTTP_POST, cookie).result.status == (String(role) == "Viewer" ? 403 : 200));
        assert(call(auth, "/api/schedule", HTTP_PUT, cookie).result.status == (String(role) == "Viewer" ? 403 : 200));
        for (const auto& path : {"/api/firmware/update", "/api/history/import", "/api/system/reset", "/api/serial"})
            assert(call(auth, path, HTTP_POST, cookie).result.status == 403);
        assert(call(auth, "/api/settings", HTTP_GET, cookie).result.status == 403);
        assert(call(auth, "/api/settings/alias", HTTP_GET, cookie).result.status == 403);
        assert(call(auth, "/api/new-endpoint", HTTP_GET, cookie).result.status == 403);
        assert(call(auth, "/api/users", HTTP_GET, cookie).result.status == 403);
        assert(call(auth, "/api/auth/settings", HTTP_PUT, cookie, {{"enabled", {"false"}}}).result.status == 403);
    }
    AuthManager rebooted(prefs, logger); rebooted.begin();
    assert(call(rebooted, "/api/state", HTTP_GET, admin).result.status == 200);
    auto records = String(reinterpret_cast<const char *>(prefs.bytes.data()), prefs.bytes.size());
    assert(records.find("correct horse battery") == String::npos);
    assert(records.find(admin.substring(18)) == String::npos);
    auto publicAccounts = call(rebooted, "/api/users", HTTP_GET, admin).result.body;
    assert(publicAccounts.find("verifier") == String::npos && publicAccounts.find("salt") == String::npos);
    epoch = 0;
    assert(call(rebooted, "/api/state", HTTP_GET, admin).result.status == 503);
    epoch = 1800000000;
    assert(call(rebooted, "/api/state", HTTP_GET, admin).result.status == 200);
    WiFi.mode = WIFI_AP | 1;
    assert(call(rebooted, "/api/users", HTTP_GET, "", {}, true).result.status == 200);
    assert(call(rebooted, "/api/users", HTTP_GET).result.status == 401);
    assert(call(rebooted, "/api/state", HTTP_GET, admin, {}, true).result.status == 403);
    assert(call(rebooted, "/api/wifi/connect", HTTP_POST, "", {}, true).result.status == 200);
    assert(call(rebooted, "/api/users/0", HTTP_DELETE, admin).result.status == 409);
    assert(call(rebooted, "/api/users/0", HTTP_PUT, admin, {{"enabled", {"false"}}}).result.status == 409);
    auto viewer = login(rebooted, "Viewer");
    assert(call(rebooted, "/api/users/1", HTTP_PUT, admin, {{"password", {"a different password"}}}).result.status == 200);
    assert(call(rebooted, "/api/state", HTTP_GET, viewer).result.status == 401);
    viewer = login(rebooted, "Viewer", "a different password");
    prefs.fail = true;
    assert(call(rebooted, "/api/users/1", HTTP_DELETE, admin).result.status == 500);
    assert(call(rebooted, "/api/state", HTTP_GET, viewer).result.status == 200);
    prefs.fail = false;
    assert(call(rebooted, "/api/users/1", HTTP_PUT, admin, {{"revokeSessions", {"true"}}}).result.status == 200);
    assert(call(rebooted, "/api/state", HTTP_GET, viewer).result.status == 401);
    auto op = login(rebooted, "Operator");
    assert(call(rebooted, "/api/users/2", HTTP_PUT, admin, {{"enabled", {"false"}}}).result.status == 200);
    assert(call(rebooted, "/api/state", HTTP_GET, op).result.status == 401);
    assert(call(rebooted, "/api/auth/logout", HTTP_POST, admin).result.status == 200);
    AuthManager afterLogout(prefs, logger); afterLogout.begin();
    assert(call(afterLogout, "/api/state", HTTP_GET, admin).result.status == 401);
    admin = login(afterLogout, "root");
    epoch += 2592001;
    assert(call(afterLogout, "/api/state", HTTP_GET, admin).result.status == 401);
    ticks += 4000;
    assert(call(afterLogout, "/api/auth/login", HTTP_POST, "", {{"username", {"root"}}, {"password", {"wrong"}}}).result.status == 401);
    assert(call(afterLogout, "/api/auth/login", HTTP_POST).result.status == 429);
    admin = login(afterLogout, "root");
    prefs.fail = true;
    assert(call(afterLogout, "/api/auth/settings", HTTP_PUT, admin, {{"enabled", {"false"}}}).result.status == 500);
    assert(call(afterLogout, "/api/state").result.status == 401);
    prefs.fail = false;
    assert(call(afterLogout, "/api/auth/settings", HTTP_PUT, admin, {{"enabled", {"false"}}}, true).result.status == 200);
    assert(call(afterLogout, "/api/state").result.status == 200);
    AuthManager disabledAfterReboot(prefs, logger); disabledAfterReboot.begin();
    assert(call(disabledAfterReboot, "/api/settings").result.status == 200);
    assert(call(disabledAfterReboot, "/api/state", HTTP_GET, "", {}, true).result.status == 403);
    assert(call(disabledAfterReboot, "/api/auth/settings", HTTP_PUT, "", {{"enabled", {"true"}}}).result.status == 200);
    assert(call(disabledAfterReboot, "/api/state", HTTP_GET, admin).result.status == 401);
    admin = login(disabledAfterReboot, "root");
    auto keyResponse = call(disabledAfterReboot, "/api/auth/ha-key", HTTP_POST, admin);
    assert(keyResponse.result.status == 200);
    String key = keyResponse.result.body.substring(8, 77);
    assert(key.length() == 69 && key.startsWith("onha_"));
    assert(prefs.keyBytes.size() == 32);
    AuthManager withKey(prefs, logger); withKey.begin();
    epoch = 0;
    assert(call(withKey, "/api/settings", HTTP_GET, "", {}, false, true, key).result.status == 200);
    assert(call(withKey, "/api/clean", HTTP_POST, "", {}, false, false, key).result.status == 403);
    assert(call(withKey, "/api/users", HTTP_GET, "", {}, false, true, key).result.status == 403);
    assert(call(withKey, "/api/auth/ha-key", HTTP_POST, "", {}, false, true, key).result.status == 403);
    assert(call(withKey, "/api/state", HTTP_GET, "", {}, false, true, "bad").result.status == 401);
    assert(call(withKey, "/api/state", HTTP_GET, "", {}, true, true, key).result.status == 403);
    assert(call(withKey, "/api/auth/ha-key", HTTP_POST, "", {}, true).result.status == 403);
    epoch = 1800000000 + 2592001;
    assert(call(withKey, "/api/auth/ha-key", HTTP_GET, admin).result.body.find(key) == String::npos);
    prefs.fail = true;
    assert(call(withKey, "/api/auth/ha-key", HTTP_DELETE, admin).result.status == 500);
    assert(call(withKey, "/api/auth/ha-key", HTTP_POST, admin).result.status == 500);
    assert(call(withKey, "/api/state", HTTP_GET, "", {}, false, true, key).result.status == 200);
    prefs.fail = false;
    auto replacement = call(withKey, "/api/auth/ha-key", HTTP_POST, admin);
    assert(replacement.result.status == 200);
    assert(call(withKey, "/api/state", HTTP_GET, "", {}, false, true, key).result.status == 401);
    key = replacement.result.body.substring(8, 77);
    assert(call(withKey, "/api/auth/ha-key", HTTP_DELETE, "", {}, true).result.status == 200);
    AuthManager revokedKey(prefs, logger); revokedKey.begin();
    assert(call(revokedKey, "/api/state", HTTP_GET, "", {}, false, true, key).result.status == 401);
    // Migrate the version-1 record prefix without losing the Admin account.
    Preferences legacy = prefs;
    legacy.bytes.resize(legacy.bytes.size() - 8);
    legacy.bytes[0] = 1;
    AuthManager migrated(legacy, logger); migrated.begin();
    assert(call(migrated, "/api/state").result.status == 200);
    assert(call(migrated, "/api/users").result.body.find("root") != String::npos);
    prefs.bytes[0] = 99;
    AuthManager corrupt(prefs, logger); corrupt.begin();
    assert(call(corrupt, "/api/state").result.status == 503);
    std::cout << "Auth regression tests passed: roles, persistence, expiry, revocation, recovery isolation, CSRF, storage failure.\n";
}
